export const QUOTES = [
    "Crokinole Dundee",
    "See You Later Alligator, in a Hole Crokinole",
    "If You Smeeeeeeell What the Crok is Cookin'",
    "Crok 'n' roll",
    "Let's Crok",
    "Put Crok in 'ole",
    "If the Van is a Crokin', Don't Come a Knockin'",
    "Get Your Croks Off",
    "We Built This City on Crokinole",
    "Crok Around the Clock",
    "Crokin' All Over the World",
    "Crok You Like a Hurricane",
    "I Wanna Crokinole All Nite (and Party Every Day)",
    "Crok the Casbah",
    "It's Only Crokinole (But I Like It)",
    "Stuck Between a Crok and a Hard Place",
    "School of Crok",
    "Crok of Ages",
    "Crocodile Crok",
    "Crok Me Amadeus",
    "You Crok My World",
    "I Love Crokinole",
    "Jailhouse Crok",
    "Crokinole Pun",
    "Crokenheimer",
    "CROK YOU 😡",
    "Crokin' hell",
    "It's crok o' clock",
    "Crok of shit",
    "Betty Crokker",
    "Crok dealer",
    "This crok is really moreish",
    "Crok Addict",
    "Smokin' crok",
    "Don't say crok, Jez, please, not now. Cause when you say crok it makes me think of crok, and I love crok.",
    "Croktails",
    "Get your hands off my crok",
    "Crok au vin",
    "Crok monsieur",
    "Crok madame",
    "Le crok sportif",
    "Crok crok, who's there?",
    "Croktor Who",
    "Birds of a feather crok together",
    "Crok her up",
    "Croks out for Harambe",
    "A Crokwork Orange",
    "The Crokinoles of Narnia",
    "Is that a crok in your pocket, or are you just pleased to see me?",
    "Croxanne",
    "Big crok energy",
    "Go hard or go Crokinole"
];
