on:
  push:
    branches:
      - develop

jobs:
  build_frontend:
    name: Build front-end components
    runs-on: ubuntu-latest
    steps:
      - name: Run npm install and build
        run: |
          cd ui
          npm install
          npm run build
    
